### ISSUE TITLE
Setup guide

### ISSUE THREAD

**Issue by haxxus** [JannoEsko/q3panel#1]
Hello , can you provide some instructions to set up ? I would like to use it for quake 3

**Comment by JannoEsko** [comment]
Hello haxxus,

After installing the panel, the primary step is to set up a host machine. Currently this does require you to run a Linux-based OS (it can be done with Windows servers as well, does need some tweaks). For the host os, you can use the root account access to make it easier to set up (my advise is to enable root account access for localhost or specific IP's if you're hosting the panel separate from the game host servers). After that, you have to set up the game, that's the tricky part and I think that's why you're here as well.

[Imgur link for Soldier of Fortune 2](https://i.imgur.com/hXDBo7p.png)

This is the example how I set it up for Soldier of Fortune 2, SoF2 is running on Quake 3 engine. Most of this can actually be used for Quake 3 as well, just need to edit some file names, remove a couple of binaries.

Startscript for SoF2:
`export LD_LIBRARY_PATH=/usr/local/games/1fxlib;ln -s /usr/local/games/base ~/base;~/sof2ded +set dedicated 2 +set vm_game 0 +set fs_game 1fx +set net_port {server_port} +set fs_homepath /home/{server_account} +set g_clientMod "RPM" +set sv_maxclients {max_clients} +exec Config.cfg +set rconpassword {rconpassword} `

More generic version:
`ln -s /usr/local/games/base ~/base;~/game_executable +set dedicated 2 +set net_port {server_port} +set fs_homepath /home/{server_account} +set sv_maxclients {max_clients} +exec Config.cfg +set rconpassword {rconpassword} `

You can give this one a try by changing game_executable to the Quake 3 server executable and the +exec Config.cfg to your server configuration file. You can also replace +exec Config.cfg with something like +map mapname. That should start the server as well. 

Game name is just a friendly name to remember the game by. Game location has to be a location, where the files, which will be copied to the new user account which the panel will create for the game server, have to exist. For SoF2, I just copied the server mod files to the server account along with the executable and configured the startscript to reference to the rest of the game files.

For Quake 3, if you got all the server files, they typically also contain the *.sh or *.bat file with them, which start the server. You can copy the contents of that file to the startscript and edit it to fit your needs. There are certain tags which get auto-replaced based on the configuration of the startscript. Those tags are shown above in my startscript and they're between curly brackets. So /home/{server_account} turns into /home/srv1, +set rconpassword {rconpassword} turns into +set rconpassword yourrconpassword and so on. A lot of this is also commented in the source code of the panel.

If you can, please share the files you already have for the server-side of Quake 3. We can figure something out.

Best regards,
Janno

**Comment by haxxus** [comment]
Great janno , well I'm familiar with q3 game hosting I have a few servers running from a centos 7 vps , I have .sh's made for each server for example here is one

#!/bin/sh
./quake3e.x64 +cvar_restart +set net_port 27961 +set dedicated 2 +set logfile 2 +set fs_homepath /var/www/html/gauntlets +set fs_basepath /root/q3e/servers/gauntlets +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec gauntlets.cfg >/dev/null 2>&1 &

I guess first step is installing the panel, i have main game servers set up on a centos machine ive already managed to set up sql, your q3panel is hosted on a debian 9 vps elsewhere i need to also set sql on it correct ?

**Comment by haxxus** [comment]
or rather should i simply host the game on the same machine , preferably debian

**Comment by JannoEsko** [comment]
Hi Haxxus,

> or rather should i simply host the game on the same machine , preferably debian

No, you can host them separately. Just to save yourself the configuration hassle (you can make an account which has specific abilities to chown, chmod, adduser, passwd), my advise is to use root and to make SSH access to it allowed only on specific IP's, so in your case, if your game server VPS is on IP 192.168.1.1 and the hosting VPS is on IP 192.168.2.2, allow root access on the game server for 192.168.2.2 IP.

`#!/bin/sh
./quake3e.x64 +cvar_restart +set net_port 27961 +set dedicated 2 +set logfile 2 +set fs_homepath /var/www/html/gauntlets +set fs_basepath /root/q3e/servers/gauntlets +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec gauntlets.cfg >/dev/null 2>&1 &`

In this case, you can set up the startscript like this:
`./quake3e.x64 +cvar_restart +set net_port {net_port} +set dedicated 2 +set logfile 2 +set fs_homepath /var/www/html/gauntlets +set fs_basepath /root/q3e/servers/gauntlets +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec gauntlets.cfg +set rconpassword {rconpassword}`

Or if you're planning to deploy the files from /var/www/html/gauntlets to the server owner account:
`./quake3e.x64 +cvar_restart +set net_port {net_port} +set dedicated 2 +set logfile 2 +set fs_homepath /home/{server_account} +set fs_basepath /root/q3e/servers/gauntlets +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec gauntlets.cfg +set rconpassword {rconpassword}`

Rconpassword should be in the startscript because the panel also has a web-based RCON utility, so you can send commands to your server without actually having the game open. But thanks to that, the panel needs to know the RCON password. That's why, on my servers, I used this method, I commented out the RCONPassword line in the configuration file and just added it into the startscript. That way, the panel will know the RCONPassword (and if you wish, you can run some extra automatic commands with it, for example, I use the RCONPassword in the CRON task to check if the players in the server are using VPN's and then automatically banning them for usage, not because I hate VPN's, but because they're using VPN's to avoid bans).

This does require you to have the game set up in a different folder with quake3e.x64 file, which will be copied to the newly made user account when you deploy a server. I used /usr/local/games as that folder. Make sure the executable has running rights for every user group (so you won't end up with errors along the way).

> I guess first step is installing the panel, i have main game servers set up on a centos machine ive already managed to set up sql, your q3panel is hosted on a debian 9 vps elsewhere i need to also set sql on it correct ?

The Q3Panel can be set up on the Debian9 VPS somewhere else and you don't need to copy any files over to the game server. The game files have to be on the game server and the game setup instructions have to be on the game server as well (the files which will be copied; the panel sends instructions on game setup over SSH to the game server). CRON will run the same way, on the hosting side, will contact the game server depending on your setup. 

Anyhow give it a go, try setting it up with that startscript I gave you, also make sure you got the game files ready on the game server.

Worth noting, the hosting server side must have at least MySQL Server 5.7, there are some minor specifics which will error out on older MySQL versions. It's also built on PHP7.0, so if you run into any errors, get PHP7.0. Another thing to note is that your game server VPS must have screen installed. The game panel uses screen to run the game instances (easier to send commands, you can also attach/detach it over SSH, easier to force-quit). 

Please, give it a try and do let me know! :)

BR,
Janno

**Comment by haxxus** [comment]
Great info , I will and will also try to set up your cron vpn method sounds great.

**Comment by JannoEsko** [comment]
Alright! Let me know how it turns out! :+1:

**Comment by haxxus** [comment]
Hello, finally made time to play with it today, well I gave up on centos 7 as I could not properly set up ssh2 , but this is not a problem I installed two debian 9's and placed p3panel on both under:
/var/www/html/q3panel/
you can see both working on:
http://173.199.123.35/q3panel
http://107.191.46.161/q3panel

Problem now is: SQLSTATE[HY000] [2002] Connection refused

My installs were as follow:
apt-get update
apt-get install screen
apt-get -y install apache2
systemctl start apache2.service
apt-get -y install mariadb-server mariadb-client 
( followed with MySQL_secure_installation used no on disallow remote root access )
apt-get install php7.0-ssh2 php7.0-curl

then I made this two databases same settings just different ip's
server 173. 
create database q3panel;
grant all privileges on q3panel.* to 'q3server'@'107.191.46.161' identified by '###' with grant option;
server 107.
create database q3panel;
grant all privileges on q3panel.* to 'q3server'@'173.199.123.35' identified by '###' with grant option;

added  # to bind-address		= 127.0.0.1 inside:
/etc/mysql/mariadb.conf.d/50-server.cnf
and am using default firewall rule on both systems:
 Chain INPUT (policy ACCEPT)
 target     prot opt source               destination

 Chain FORWARD (policy ACCEPT)
 target     prot opt source               destination

 Chain OUTPUT (policy ACCEPT)
 target     prot opt source               destination 


![installation q3panel - google chrome](https://user-images.githubusercontent.com/24307265/33529144-63c4f9c8-d83a-11e7-8b73-9a5dc840b6c5.jpg)

wasn't sure about the panel url location so I just used an empty location assuming it creates it.

soo .. this is where I'm at :( .

**Comment by JannoEsko** [comment]
Hmm, on what port is the DB running on? My program might be running on default (which is actually an issue and I should give it a look). This might be a case where the DB on your server runs on a different port and my panel can't communicate with it this way.

MySQL/MariaDB should both run on 3306, but if you changed that in the config, a quick workaround is to change the DSN in the SQL class:

https://github.com/JannoEsko/q3panel/blob/master/classes/sql/SQL.php#L43

Change the line to:
`return "mysql:host=$host;dbname=$db;port=YOURPORT";`

Also worth noting, I'm not 100% sure if current MariaDB supports everything what MySQL 5.7 supports, one of the users did have an issue with MySQL 5.5 over some SQL constraints, but then again, he did manage to get a connection to the db.

**Comment by haxxus** [comment]
Morning :) , well I replaced the line you suggested it kept giving same problem so I kept researching and found MySQL both mariadb and 5.7 default settings are to only listen on localhost so I edited:
/etc/mysql/mysql.conf.d/mysqld.cnf
adding # on bind-address	= 127.0.0.1
and now I get this:
Couldn't open file /var/www/html/q3panel/classes/installation/../../config.php for writing. Please recheck permissions!

  well some progress :) I tried to find that file on error but I don't see it

**Comment by JannoEsko** [comment]
Hi haxxus,

Give permissions to /var/www/html/q3panel/ to www-data with chown and
delete config.php from that folder and try again.

Br,
Janno

**Comment by haxxus** [comment]
did:
chown -R www-data:www-data  /var/www/html/q3panel/

**Comment by haxxus** [comment]
and now I see this error:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'q3panel_users' already exists

if I refresh the page I get page not found 500 error , if I go back to /install I get:

Notice: Undefined variable: Kj in /var/www/html/q3panel/config.php on line 3

Notice: Undefined variable: ogQ58H in /var/www/html/q3panel/config.php on line 3

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'q3server'@'173.199.123.35' (using password: YES) in /var/www/html/q3panel/classes/sql/SQL.php:21 Stack trace: #0 /var/www/html/q3panel/classes/sql/SQL.php(21): PDO->__construct('mysql:host=107....', 'q3server', '7}GA,{', Array) #1 /var/www/html/q3panel/config.php(3): SQL->__construct('107.191.46.161', 'q3server', '7}GA,{', 'q3panel') #2 /var/www/html/q3panel/classes/loader.php(14): require_once('/var/www/html/q...') #3 /var/www/html/q3panel/functions.php(15): require_once('/var/www/html/q...') #4 /var/www/html/q3panel/install/index.php(6): require_once('/var/www/html/q...') #5 {main} thrown in /var/www/html/q3panel/classes/sql/SQL.php on line 21

**Comment by haxxus** [comment]
deleted q3server database to clear all the tables and re registered it, after entering the info on step 2 , I see it does some tasks and takes me to an empty blank page step 3

http://173.199.123.35/q3panel/install/step3/ , if I go back to /install , same Uncaught PDOException: error

**Comment by JannoEsko** [comment]
> Notice: Undefined variable: Kj in /var/www/html/q3panel/config.php on line 3
Notice: Undefined variable: ogQ58H in /var/www/html/q3panel/config.php on line 3

Now that's an odd issue, can you copy the contents of config.php over here (remove password(s) tho or replace them with ***).

**Comment by haxxus** [comment]
yep 

`<?php

$sql = new SQL("107.191.46.161", "q3server", "*******", "q3panel");


$HOST_URL = "http://173.199.123.35/panel";`

this is the only thing in config.php

**Comment by haxxus** [comment]
![107 191 46 161 localhost q3panel phpmyadmin 4 6 6deb4 and 4 more pages - microsoft edge](https://user-images.githubusercontent.com/24307265/33674774-7e60e814-da7e-11e7-81a8-3e5bb10c9435.jpg)

more info found, creates the databases

**Comment by JannoEsko** [comment]
Does your SQL password contain the letter $?

**Comment by haxxus** [comment]
yes , twice!

**Comment by haxxus** [comment]
shall I remove them  ?

**Comment by JannoEsko** [comment]
Escape them. Like so, if your password is $kf$9999$blabla, then:
`\$kf\$9999\$blabla`

Do that edit in config.php, this is a bug which does need to be fixed tho. 👍

**Comment by haxxus** [comment]
another question, if I change ssh / ssh2 port, should I enter port info somewhere in the q3panel tool ? seems not went on to step 3! , nice ill continue tomorrow

**Comment by haxxus** [comment]
And now I'm stuck in step4 haha , well I'm not sure if I should install something for sendgrid , I did install sudo apt-get install sendmail

should I configure something else on the server before pressing one of the buttons ? my initial choice was sendgrid but seeing it doesn't do anything I opt to phpmailer after installing sendmail,  but both buttons aren't doing anything after being pressed. 

Edit, umm seems to be an issue with chrome , I'm seeing the sendgrid menu from edge

**Comment by haxxus** [comment]
![homepage q3panel and 2 more pages - microsoft edge](https://user-images.githubusercontent.com/24307265/33683449-f17a53c0-da98-11e7-86bb-2a1776f281b4.jpg)

I'm in :)

**Comment by haxxus** [comment]
So far so good until I try to add a server, with the right info after I press submit it doesn't do anything nor gives me an error, now if I change username or password incorrectly then I get:

Something went wrong with your action, please, check the data you provided (if any), try again or refresh the page and try again.

so is working but not registering the server details ? 
I'm logging in as root and have
PermitRootLogin yes
on /etc/ssh/sshd_config

**Comment by haxxus** [comment]
possibly a misconfiguration on my side ?

**Comment by JannoEsko** [comment]
Might be that the account already exists in the system. You can try adding another server account, try using srv100 or so. The panel wants to create a new account, that's why. :)

When adding the server, you can leave a lot of the fields blank. Only fields which are required, are Server name, Max clients and RCONPassword. Rest will be auto-set if you got game and host set up. You can add an FTP account tho but name it into something which doesn't already exist on your system.

**Comment by haxxus** [comment]
great, I'm learning a lot from all this :) . Will swim back into it now, I ended up deleting main vps I was testing q3panel and reinstalling a new one, thing is I'm trying to properly setup a wordpress setup on the same machine main q3panel will be , so for example main with q3panel/wordpress in new York and game host on paris, finally got it set up last night perfectly for wordpress following these two guides:
https://www.linuxtechbits.com/install-lamp-server-debian-9-stretch/
https://www.linuxtechbits.com/install-wordpress-in-debian-9-stretch/
but instead of mariandb I followed this guide for MySQL 5.7
https://www.globo.tech/learning-center/install-mysql-5-7-debian-9/
   So far so good I have wordpress working perfectly now q3panel! :)

**Comment by haxxus** [comment]
umm question should I do the install steps from both sides or only from web q3panel host to game server host? 

Wondering how main panel finds the location of the game host panel, so for example if ive set my main html directory to:
/var/www/example.com/html with my main website files here and q3panel folder so q3panel will display on:
example.com/q3pnael

but then on my game host should I do the same or move q3panel files directly to the html folder ?

**Comment by haxxus** [comment]
Ok so I used Paris ( game server ) server from main host following install steps, shouldn't it show under servers after install because its not showing, if not is there a way to delete it from the back end so it lets me add it from the panel, I understand it might be setup internally but I would like it to show on my front end if possible.

**Comment by haxxus** [comment]
So in other words ive set up server A containing q3panel with B following the initial setup steps, but once inside the panel I cant see b server nor add it. 
Or am I missing something / not understanding something .. 
   Ive setup everything on server B like so:

game files in /home/quake3/ ( so here ive placed baseq3 and the .ded )
server files in /home/quake3/servers/servername/ ( here I have the mod folder with configs )

so my string so far is:

./quake3e.x64 +cvar_restart +set net_port 27960 +set dedicated 2 +set logfile 2 +set fs_homepath /home/quake3/servers/servername +set fs_basepath /home/quake3/ +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec freon-server.cfg +set rconpassword xxxxx

This way I hope to be able to create more games under same server using same baseq3 so servers share the same basepath but not homepath as homepath will be different for each .

**Comment by haxxus** [comment]
Just tried adding a different host to the list, same problem when I press submit just hangs there :(

**Comment by haxxus** [comment]
aha look what I found maybe this helps:
![hosts q3panel - google chrome](https://user-images.githubusercontent.com/24307265/33810847-37d31a2c-ddd8-11e7-891d-f9e8117e6c53.jpg)

**Comment by haxxus** [comment]
more info:

[Sun Dec 10 23:27:19.532163 2017] [:error] [pid 28874] [client x.x.x.x.x.x:1608                                                                                                                                                                                                                                             3] PHP Notice:  Undefined index: stderr in /var/www/okayfun.com/html/q3panel/cla                                                                                                                                                                                                                                    sses/servers/host/Host.php on line 170, referer: http://45.76.167.25/q3panel/hos                                                                                                                                                                                                                                             ts/
[Sun Dec 10 23:27:19.532245 2017] [:error] [pid 28874] [client x..xx.x.x.:1608                                                                                                                                                                                                                                             3] PHP Notice:  Undefined index: stdio in /var/www/okayfun.com/html/q3panel/clas                                                                                                                                                                                                                                             ses/servers/host/Host.php on line 173, referer: http://45.76.167.25/q3panel/host                                                                                                                                                                                                                                             s/
[Sun Dec 10 23:28:45.223933 2017] [:error] [pid 29029] [client x.x.x.:1613                                                                                                                                                                                                                                             0] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22003]: Numeric value out o                                                                                                                                                                                                                                             f range: 1264 Out of range value for column 'sshport' at row 1 in /var/www/okayf                                                                                                                                                                                                                                             un.com/html/q3panel/classes/sql/SQL.php:33\nStack trace:\n#0 /var/www/okayfun.co                                                                                                                                                                                                                                             m/html/q3panel/classes/sql/SQL.php(33): PDOStatement->execute(Array)\n#1 /var/ww                                                                                                                                                                                                                                             w/okayfun.com/html/q3panel/classes/servers/host/Host.php(177): SQL->query('INSER                                                                                                                                                                                                                                             T INTO q3p...', Array)\n#2 /var/www/okayfun.com/html/q3panel/functions.php(828):                                                                                                                                                                                                                                              Host->addHost(Object(SQL))\n#3 {main}\n  thrown in /var/www/okayfun.com/html/q3                                                                                                                                                                                                                                             panel/classes/sql/SQL.php on line 33, referer: http://45.76.167.25/q3panel/hosts                                                                                                                                                                                                                                             /

**Comment by haxxus** [comment]
ok had a friend look into it and found out in q3panel database, there is a table called q3panel_hosts, if you see the structure of this table you'll find it that sshport was set to tinyint(4), my port was higher 5 digits so he altered the table and made the sshport field to int(11) , now it registered perfectly :) will continue the rest soon .

**Comment by haxxus** [comment]
when creating folders on web ftp says successful but I don't see them, is main web ftp supposed to look like this ?
![web ftp interface q3panel and 4 more pages - microsoft edge](https://user-images.githubusercontent.com/24307265/33902115-01f31540-df42-11e7-896f-0d6993e29a51.jpg)

and when I try to create a file I get: 
![web ftp interface q3panel and 4 more pages - microsoft edge_2](https://user-images.githubusercontent.com/24307265/33902146-17af220c-df42-11e7-92f0-af945c169457.jpg)

**Comment by JannoEsko** [comment]
> ok had a friend look into it and found out in q3panel database, there is a table called q3panel_hosts, if you see the structure of this table you'll find it that sshport was set to tinyint(4), my port was higher 5 digits so he altered the table and made the sshport field to int(11) , now it registered perfectly :) will continue the rest soon .

Hmm, odd, I thought I fixed the SSH port issue already, stumbled across it once myself when I changed my own SSH port from the default one and it errored out due to the SQL issue, good find.


> when creating folders on web ftp says successful but I don't see them, is main web ftp supposed to look like this ?

Now this is odd. FTP does require you to have the PHP FTP extension installed AND the FTP for the server-side installed as well (e.g. proftpd), also requires you to let the server accounts have access to the FTP. I used DefaultRoot to lock them into their own home folder but allowed access for everyone. Did disable access for SFTP tho.

Sorry for inactivity, been a bit busy lately. Do the servers run tho?

**Comment by haxxus** [comment]
Hey glad your back :) well yeah I don't have any ftp setup only sftp , so I will try to figure out how to run proftpd, give access to the server account try defaultroot , or would it be simpler to convert it into sftp mode ? 
And no lol I tried to run the server the page returned the server started but nothing ran on the vps , i'm actually a bit confused as to how it creates the game servers directory let me explain.

For me the plan is to create more Game servers on the same vps host, so I created a game called quake3 using /home/quake3/mods as game location where I have mods folder ( fs_homepath )
inside /home/quake3 ( fs_basepath ) is where I have the  baseq3 and quake3e.x64
Notice when I create a game server it copies game location files inside given ftp name on to /home 
 For example if I enter this:

 
![servers q3panel - google chrome](https://user-images.githubusercontent.com/24307265/33942076-d28aa236-dfe2-11e7-9483-78e5656c2559.jpg)

then it creates a 'freon' user with ftp access ( in my case sftp, so not working from webFTP ) copies all files inside /home/quake3/modes inside Freon folder on /home . 

Is this the way is supposed to do it /home being a fixed location ? My start script is:

./quake3e.x64 +cvar_restart +set net_port 27960 +set dedicated 2 +set logfile 2 +set fs_homepath /home/quake3/mods +set fs_basepath /home/quake3/ +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword dsf@#^&&ggjj! +set map test_bigbox +exec server.cfg 

and I also tried fs_homepath /home/freon  ( didn't work ) thinking it needs the game server location , but this is what's got me a bit confused.

**Comment by haxxus** [comment]
friend who fixed the ftp portion did:

File location /var/www/html/q3panel/classes/ftp/FTP.php

Added the ftp_pasv($this->ftp, true); in the construct so that it can pass through the firewall, else the file was created but no content was there to display.

Rewrite getFileContents() method
$tempFile = fopen('php://temp', 'r+');
ftp_fget($this->ftp, $tempFile, $filename, FTP_BINARY, 0);
$fstats = fstat($tempFile);
fseek($tempFile, 0);
$contents = fread($tempFile, $fstats['size']);
return array('filecontents' => $contents);

Storing the ftp text file data in local php memory and then returning the content on filecontents key

Rewrite createNewFile() method

$location = rtrim($location, "/") . "/" . $newfilename;
$tempFile=fopen('php://temp', 'r+');
fwrite($tempFile, $newfilecontents);
rewind($tempFile);

return ftp_fput($this->ftp, $location, $tempFile, FTP_ASCII);

Storing in temp variable and the using ftp_fput the file will created on the FTP server

Rewrite writeFile() method

file_gets_content() replaced with temp variables and also this method deletes the file

$tempFile=fopen('php://temp', 'r+');
fwrite($tempFile, $filecontents);
rewind($tempFile);

return ftp_fput($this->ftp, $filename, $tempFile, FTP_ASCII);

there were a few issues after configuring the ftp , now is working perfectly , only problem remaining so far is starting the game

**Comment by JannoEsko** [comment]
> And no lol I tried to run the server the page returned the server started but nothing ran on the vps , i'm actually a bit confused as to how it creates the game servers directory let me explain.

Check if your VPS has screen installed. Type in screen -ls and see if it outputs something.

Another way I have tested the startscript is by running it straight in the shell and seeing if it works like that.

> Is this the way is supposed to do it /home being a fixed location


Yes, currently it's set up in a way that it uses the /home/serveraccount to store the files it copies. That can be changed inside the code itself, if not mistaken, inside Constants.php (tried to keep most of the action commands straight in that file).

The FTP not working still remains a mystery for me because it worked quite fine for me, albeit I didn't test it while being behind a firewall, some issues might've arised from that.

Please test the server startscript (the server 1, not the game 1, replace the replaceable tags, e.g. {net_port} and {rconpassword}) in the shell and see if the game starts. If it doesn't, it typically shows you the error why it didn't. From my experience, that problem boils down in some libraries being missing or the executable not having chmod +x. Please give it a try and let me know if it works. :)

**Comment by haxxus** [comment]
screen info:
root@vultr:~# screen -ls
No Sockets found in /run/screen/S-root.

Yes I can start the game from shell, right now I've changed the config to a working copy paste from my centos server to make sure 100 percent I had game settings correct so I ran it from shell and worked perfect , this is what i'm using now:

./quake3e.x64 +cvar_restart +set net_port 27960 +set dedicated 2 +set logfile 2 +set fs_homepath /home/freon +set fs_basepath /home/quake3 +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword dfsdfsdf +exec skeeter.cfg

same setting on the game server 
![server management q3panel and 7 more pages - microsoft edge](https://user-images.githubusercontent.com/24307265/33999128-98a06148-e0b7-11e7-9c1e-854f08ba15fe.jpg)

and question I see a max client setting on the panel ,  this sets the max client on the game so I don't have to use:
 set sv_maxclients "x" on the server .cfg ?

**Comment by JannoEsko** [comment]
Does your startscript have dedicated set to 2? Does it start a map?

**Comment by haxxus** [comment]
question from my friend who is helping me set it up:

script is running from the terminal but not executing from the code, file location var/www/html/classes/ssh/SSH.php 
method sendCommand();

the script from the panel found was: 
screen -d -S bilal -m sh -c "./quake3e.x64 +cvar_restart +set net_port 27960 +set dedicated 2 +set logfile 2 +set fs_homepath /home/freon +set fs_basepath /home/quake3 +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword dfsdfsdf +exec skeeter.cfg"

and I tested running from screen and it works on shell wile in the /home/quake3 directory

**Comment by haxxus** [comment]
yes dedicated set to 2 , and yes it starts from shell I went in the server a few times and all

**Comment by JannoEsko** [comment]
`screen -d -S bilal -m sh -c "./quake3e.x64 +cvar_restart +set net_port 27960 +set dedicated 2 +set logfile 2 +set fs_homepath /home/freon +set fs_basepath /home/quake3 +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword dfsdfsdf +exec skeeter.cfg"`

Please use ~/quake3e.x64, so it most definitely is in the right folder (or point it to a folder where it should be, currently it might be in a wholely different folder, it's a possibility).

Anyhow, the command does seem fine and as I understood, when you run that command straight in the shell as the server account, it works as well?

Method string derives from Constants.php
`"START_SERVER" => "screen -d -S {server_account} -m sh -c \"{server_startscript}\"" `
It does require you to have the quote marks inside the startscript to be escaped, but you don't have any quotes in the startscript so that's good.

Also on your server startscript, you should use replaceable tags.

`./quake3e.x64 +cvar_restart +set net_port {net_port} +set dedicated 2 +set logfile 2 +set fs_homepath /home/{server_account}+set fs_basepath /home/quake3 +set fs_game excessiveplus +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword {rconpassword} +exec skeeter.cfg`

Worth noting, that the panel expects the base game files to be at /home/server_account, under base, as we've discussed, should be the essential executables and the files which might differ from the other server files, so the quake3e.x64 and the mod files.


> and question I see a max client setting on the panel , this sets the max client on the game so I don't have to use:
set sv_maxclients "x" on the server .cfg ?

Yes, yet again it's a replaceable tag. Add `+set sv_maxclients {max_clients}` to the startscript and you can remove the stuff from the server config. My main server has the startscript like this:

`export LD_LIBRARY_PATH=/usr/local/games/1fxlib;ln -s /usr/local/games/base ~/base;~/sof2ded +set dedicated 2 +set vm_game 0 +set fs_game 1fx +set net_port {server_port} +set fs_homepath /home/{server_account} +set g_clientMod "RPM" +set sv_maxclients {max_clients} +exec Config.cfg +set rconpassword {rconpassword} `

I use ln to get the game base files for the game.

**Comment by JannoEsko** [comment]
Which version of Q3 server stuff are you using? Can you share any links so I can try to set it up myself and share the way I set it up with you?

**Comment by haxxus** [comment]
im using 1.32e from http://edawn-mod.org/

paired with excessiveplus mod https://www.excessiveplus.net/

**Comment by JannoEsko** [comment]
Cheers, I'll give it a go over the weekend and will let you know if I got it working and how I did. Thank you for your support and time haxxus for messing around with this project, never expected anyone except myself to use it... ;)

**Comment by haxxus** [comment]
aha no i plan to use it were a few bunch of players and so far i lend my vps presetup to run quake3 servers to a few server admins , this tool will make it very simple to keep things organized/managed.
 I tried your command from shell seems it wants to look inside /root/ even when i logged in from the panel user

`
export LD_LIBRARY_PATH=/home/freon;ln -s /home/quake3 ~/quake3;~/quake3e.x64 +set dedicated 2 +set vm_game 0 +set fs_game excessiveplus +set net_port 27960 +set fs_homepath /home/{server_account} +set sv_maxclients 7 +set logfile 2 +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec skeeter.cfg +set rconpassword test`
ln: failed to access '/root/quake3': Permission denied
bash: /root/quake3e.x64: Permission denied


after trying from panel and failed:
`export LD_LIBRARY_PATH=/home/freon;ln -s /home/quake3 ~/quake3;~/quake3e.x64 +set dedicated 2 +set vm_game 0 +set fs_game excessiveplus +set net_port {server_port} +set fs_homepath /home/{server_account} +set sv_maxclients {max_clients} +set logfile 2 +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +exec skeeter.cfg +set rconpassword {rconpassword} `

**Comment by haxxus** [comment]
help :)

**Comment by JannoEsko** [comment]
Don't ln files from /home directory as they might have some restrictive permissions, put the Quake 3 files into e.g. /usr/games folder. Also the export LD_LIBRARY_PATH part is irrelevant for you as I doubt Quake 3 needs you to have some specific libraries while my server mod did.

Anyhow this is really odd, it shouldn't direct you to root account at all. When you're in the server account shell, type in `pwd`, see what it outputs.

**Comment by JannoEsko** [comment]
Hi

So I gave it a try just to get it running in the shell, downloaded Quake3 and excessive plus. The server started fine with little to none configuration.

`janno@vps368549:~/q3/132$ ./quake3e.ded.x64 +cvar_restart +set net_port 27500 set dedicated 2 +set logfile 2 +set com_hunkmegs 150 +set vm_rtChecks 0 +set rconpassword camel +map q3ctf1
`

I will try to make it so that it's possible to run it in the panel as well and will return with results.

**Comment by JannoEsko** [comment]
Okay, I got it working no probs. Downloaded Quake3, edawn, xp.

This is the setup:


janno@vps368549:/usr/games$ ls

baseq3  q3

janno@vps368549:/usr/games$


Baseq3 has all the base files which I will ln to the game server account so these don't need to be copied every time.
q3 folder:

janno@vps368549:/usr/games/q3$ ls

edawn  quake3e  quake3e.ded  quake3e.ded.x64  quake3e.x64

janno@vps368549:/usr/games/q3$


Here I keep the edawn mod, where you can also include some config files specific to your server. On SoF2, you can also upload custom maps to that folder and they work, so you don't add them to every server (you can also do that if you don't want server owners to copy-paste all the maps to every deployed server). Worth noting, that both folders have been chmodded to a+rw and the executable is chmodded as 777.

Q3Panel side:

![image](https://user-images.githubusercontent.com/8655217/34245806-5bf64c80-e634-11e7-81de-d3f4b2d368f7.png)


Game setup:



![image](https://user-images.githubusercontent.com/8655217/34245788-4583d62a-e634-11e7-8d2f-740e429d2b4d.png)

So the game location is /usr/games/q3, that's where I keep the files which will be copied to the server account (gotta keep them separate so separate servers can have separate configurations). That has the excessiveplus in it and also the server executables.

Startscript:
`ln -s /usr/games/baseq3 ~/baseq3;~/quake3e.ded.x64 +cvar_restart +set net_port {server_port} +set dedicated 2 +set fs_homepath /home/{server_account} +set fs_game excessiveplus +set logfile 2 +set com_hunkmegs 150 +set vm_rtChecks 0 +set ttycon 0 +set rconpassword {rconpassword} +set sv_maxclients {max_clients} +map q3ctf1`

As I didn't create a configuration script for the server, I just added map q3ctf1 instead so the server would start. ln -s at start links the baseq3 folder to the server account so we can access the base files without copying them. Rest is basically copy-paste of your serverscript, only I used the .ded.x64 executable, don't know if there's a difference but ded usually means dedicated, i.e. public server, so maybe check that one out. 

And the server is running normally. GameTracker managed to contact it and get info and also the web-based RCON works as well, so all is good!

Give it a go, doing it the same way I did and let me know! ;)

BR,
Janno

**Comment by haxxus** [comment]
Great, will be back home after the 25th and will follow your every step , thanks!

**Comment by JannoEsko** [comment]
Worth noting that I deployed the server with only server port being specified, so it automatically made all the required accounts.

**Comment by JannoEsko** [comment]
Hello haxxus,

Any luck?

BR,
Janno

**Comment by haxxus** [comment]
Hey Janno, I got back from vacation a few days ago :) .Well I tried again but I guess is not happening for me, i fear possibly a package missing or somehow the databases are not communicating as they should. 

Would it be possibly we meet on a chat app and i give you a fresh set of debian servers for you to work your magic and i can possibly note down the steps you took. It would be a blessing i can install any chat app if i don't already have it , irc , discord , skype , icq , you name it. 

If you can't no worries i will keep banging my head a bit possibly start from 0 again might be simpler.

**Comment by JannoEsko** [comment]
Hello

Sure, it's okay for me, Skype, Telegram, Whatsapp?

Janno

**Comment by haxxus** [comment]
Great!

**Comment by haxxus** [comment]
Jannoooo :)

**Comment by JannoEsko** [comment]
Sorry, added you now.

**Comment by haxxus** [comment]
Ya , I wrote there you see my msg ?

**Comment by JannoEsko** [comment]
Closed as issue is fixed. This long conversation also has a lot of points on how to set it up.

**Comment by joker124141** [comment]
hello,

How to install this q3panel on linux
